                      T
                     TTT
                  TTTTTTTTT
               TTTTTTTTTTTTTTT
                      T
                     TTT
                  TTTTTTTTT
               TTTTTTTTTTTTTTT
                      T
                     TTT
                  TTTTTTTTT
               TTTTTTTTTTTTTTT
                     TTT
                     TTT
